export const language: "en" | "ko" = localStorage.getItem("lang")
  ? (localStorage.getItem("lang") as "en" | "ko")
  : "en";

export const lang = {
  en: {
    subHeading: "Feeling Lucky?",
    heading: "Pull Out The Sword!",
    offlineModeButton: "Offline Mode",
    onlineModeButton: "Online Mode",
    chanceLockedDropdown: "Chance Locked",
    setChanceDropdown: "Chance (%): ",
    howToPlayDropdown: "How to Play",
    leaderboardButton: "Leaderboard",
    tries: "tries",
    pulls: "pulls",
    triesDropdown: "Tries",
    pullsDropdown: "Pulls",
    tppLDropdown: "TPP (L)",
    tppHDropdown: "TPP (H)",
    you: "You",
    statisticsButton: "Statistics",
    settingsButton: "Settings",
    generalDropdown: "General Settings",
    userDropdown: "User Settings",
    manual1: "Pull The Sword Out",
    manual11:
      "You can pull the sword out by clicking on the sword stuck in the stone.",
    manual12: "Beware, the chance to succeed is 1%!",
    manual2: "Leaderboard",
    manual21:
      "Since the cooldown is based on the username, sharing the username is allowed.",
    manual22:
      "But careful! Inappropriate usernames can be banned from the leaderboard.",
    manual3: "Offline Mode",
    manual31:
      "In offline mode, the leaderboard and statistics will be disabled.",
    manual32:
      "However, there will be no cooldown, and you can change your chances of succeeding!",
    manual4: "TPP (Tries per Pull)",
    manual41:
      "TPP (Tries per Pull) shows how many attempts are needed to pull the sword out.",
    manual42:
      "A lower value shows they need fewer attempts to pull the sword out, which means they're lucky.",
    manual43:
      "A higher value shows they need more attempts to pull the sword out, which means they're unlucky.",
    manual44: "The lower, the merrier!",
    statistics1: "Username",
    statistics2: "Times Tried",
    statistics3: "Times Pulled",
    statistics4: "TPP (Tries per Pull)",
    na: "N/A",
    tpp: "Tries per Pull",
    sfxVolume: "Sfx Volume",
    reducedMotion: "Reduced Motion",
    language: "Language",
    english: "English",
    korean: "Korean",
    yourNickname: "Your Nickname",
    usernameDiscretion: "This will appear on the leaderboard.",
    success: "Success!",
    failed: "Failed!",
    ok: "OK",
    close: "Close",
    stone: "Stone",
    sword: "Sword",
    dust: "Dust",
    availableIn: "Available in",
    seconds: "s",
    somethingWentWrong: "Warning!",
    inappropriateUsername: "Inappropriate Username!",
    invalidUsername: "Invalid Username!",
    usernameGuide1: "The username must contain 4 to 16 characters including...",
    usernameGuide2: "Alphabet Letters (a-z, A-Z)",
    usernameGuide3: "Numbers (0-9)",
    usernameGuide4: "Underscores (_)",
    tooManyRequest: "Action is still on cooldown.",
  },
  ko: {
    subHeading: "운이 좋으신가요?",
    heading: "검을 뽑아보세요!",
    offlineModeButton: "오프라인 모드",
    onlineModeButton: "온라인 모드",
    chanceLockedDropdown: "확률 잠김",
    setChanceDropdown: "확률 (%): ",
    howToPlayDropdown: "플레이 방법",
    leaderboardButton: "리더보드",
    tries: "시도",
    pulls: "뽑음",
    triesDropdown: "시도",
    pullsDropdown: "뽑음",
    tppLDropdown: "TPP (L)",
    tppHDropdown: "TPP (H)",
    you: "당신",
    statisticsButton: "통계",
    settingsButton: "설정",
    generalDropdown: "게임 설정",
    userDropdown: "유저 설정",
    manual1: "검을 뽑아보세요!",
    manual11:
      "메인 화면의 돌에 박힌 검을 클릭하여 검 뽑기를 시도할 수 있습니다.",
    manual12: "주의하세요, 뽑기에 성공할 확률은 단 1%입니다!",
    manual2: "리더보드",
    manual21:
      "검 뽑는 대기 시간이 사용자 이름에 따라 다르므로 사용자 이름 공유가 허용됩니다.",
    manual22:
      "하지만 조심하세요! 부적절한 사용자 이름은 리더보드에서 제외될 수 있습니다.",
    manual3: "오프라인 모드",
    manual31: "오프라인 모드에서는 리더보드와 통계 기능이 비활성화됩니다.",
    manual32:
      "하지만 검 뽑는 대기 시간이 존재하지 않으며 뽑기에 성공할 확률을 지정할 수 있습니다!",
    manual4: "TPP (Tries per Pull)",
    manual41:
      "TPP (Tries per Pull)는 검을 성공적으로 뽑는 데 필요한 시도 횟수를 의미합니다.",
    manual42:
      "값이 낮을수록 검을 뽑기 위해 더 적은 시도가 필요함을 나타내며 이는 운이 좋다는 것을 의미합니다.",
    manual43:
      "값이 클수록 검을 뽑기 위해 더 많은 시도가 필요함을 나타내며 이는 운이 좋지 않다는 것을 의미합니다.",
    manual44: "낮을수록 좋습니다!",
    statistics1: "사용자 이름",
    statistics2: "시도 횟수",
    statistics3: "뽑은 횟수",
    statistics4: "TPP (Tries per Pull)",
    na: "해당 없음",
    tpp: "Tries per Pull",
    sfxVolume: "효과음 볼륨",
    reducedMotion: "효과 최소화",
    language: "언어",
    english: "영어",
    korean: "한국어",
    yourNickname: "당신의 이름",
    usernameDiscretion: "위의 이름이 리더보드에 표시됩니다.",
    success: "성공!",
    failed: "실패!",
    ok: "확인",
    close: "닫기",
    stone: "돌",
    sword: "검",
    dust: "가루",
    availableIn: "다시 검을 뽑기까지",
    seconds: "초",
    somethingWentWrong: "경고!",
    inappropriateUsername: "사용자 이름이 부적절합니다!",
    invalidUsername: "사용자 이름이 잘못되었습니다!",
    usernameGuide1:
      "사용자 이름은 4~16자 이내여야 하며, 다음 이외에 문자의 사용은 금지됩니다.",
    usernameGuide2: "알파벳 문자 (a-z, A-Z)",
    usernameGuide3: "숫자 (0-9)",
    usernameGuide4: "밑줄 문자 (_)",
    tooManyRequest: "아직 검을 뽑을 수 없습니다.",
  },
};
